# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jstcpp <- function(dfm, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_) {
    .Call('_rJST_jstcpp', PACKAGE = 'rJST', dfm, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_)
}

jstcppreversed <- function(dfm, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_) {
    .Call('_rJST_jstcppreversed', PACKAGE = 'rJST', dfm, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_)
}

gibbsldacpp <- function(dfm, numTopics, numiters, alpha_, beta_) {
    .Call('_rJST_gibbsldacpp', PACKAGE = 'rJST', dfm, numTopics, numiters, alpha_, beta_)
}

sldacpp <- function(sfm, documentVector, sentenceVector, numTopics, numiters, alpha_, beta_) {
    .Call('_rJST_sldacpp', PACKAGE = 'rJST', sfm, documentVector, sentenceVector, numTopics, numiters, alpha_, beta_)
}

asumcpp <- function(sfm, documentVector, sentenceVector, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, alpha, gamma, betaVec) {
    .Call('_rJST_asumcpp', PACKAGE = 'rJST', sfm, documentVector, sentenceVector, sentiWords, sentiCategory, numSentiLabs, numTopics, numiters, alpha, gamma, betaVec)
}

topNwordSeeds <- function(wordParameters, N) {
    .Call('_rJST_topNwordSeeds', PACKAGE = 'rJST', wordParameters, N)
}

