# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jstcpp <- function(dfm, sentiLexList, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_) {
    .Call('_rJST_jstcpp', PACKAGE = 'rJST', dfm, sentiLexList, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_)
}

jstcppreversed <- function(dfm, sentiLexList, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_) {
    .Call('_rJST_jstcppreversed', PACKAGE = 'rJST', dfm, sentiLexList, numSentiLabs, numTopics, numiters, updateParaStep, alpha_, beta_, gamma_)
}

